name: Assignment 11
on: [push]
jobs:
  automated_test:
    name: Test find_lowest_number.py for Assignment 11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run find_lowest_number on the first test case (10 numbers).
      run: python find_lowest_number.py test_data/test1_input.txt lowest_number1.txt
    - name: Compare expected output of first test case to actual.
      run: diff lowest_number1.txt test_data/test1_actual.txt
    - name: Run find_lowest_number on the second test case (1 number).
      run: python find_lowest_number.py test_data/test2_input.txt lowest_number2.txt
    - name: Compare expected output of second test case to actual.
      run: diff lowest_number2.txt test_data/test2_actual.txt
    - name: Run find_lowest_number on the third test case (empty file).
      run: python find_lowest_number.py test_data/test3_input.txt lowest_number3.txt
    - name: Compare expected output of first test case to actual.
      run: diff lowest_number3.txt test_data/test3_actual.txt
